name: screenshot-action

run-name: Screenshot with visual regression test

on:
  deployment_status:

jobs:
  test-screenshot:
    if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - uses: actions/checkout@v4

      - name: CI Building Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Archive visual regression failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-regression-diff
          path: images/__diff_output__/
          retention-days: 10
